#!/usr/bin/env node
/**
 * Cordova iOS hooks for Document Reader:
 * - after_prepare / before_build: write build-extras.xcconfig + sign script
 * - after_build: re-sign docsdk (+ nested dcrcore) inside the built .app / .xcarchive
 */
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');


const IOS_BUNDLE_ID = 'com.identixia.documentreader.app';
const PLUGIN_ID = 'document-reader-cordova';


function readTeamId(projectRoot) {
  if (process.env.DEVELOPMENT_TEAM) return process.env.DEVELOPMENT_TEAM;
  const buildJson = path.join(projectRoot, 'build.json');
  if (!fs.existsSync(buildJson)) return null;
  try {
    const cfg = JSON.parse(fs.readFileSync(buildJson, 'utf8'));
    return (
      cfg?.ios?.debug?.developmentTeam ||
      cfg?.ios?.release?.developmentTeam ||
      null
    );
  } catch {
    return null;
  }
}


/**
 * Beginners drop Drive's docsdk.framework here. This is the single source of truth.
 * Cordova otherwise keeps a stale copy under platforms/plugins after the first add.
 */
function resolveDocsdkDropPath(projectRoot) {
  const drop = path.join(
    projectRoot,
    'DocumentReaderPlugin',
    'src',
    'ios',
    'Frameworks',
    'docsdk.framework'
  );
  if (fs.existsSync(path.join(drop, 'docsdk'))) return drop;
  // Fallback when running from a published plugin layout only.
  const pluginSrc = path.join(
    projectRoot,
    'plugins',
    PLUGIN_ID,
    'src',
    'ios',
    'Frameworks',
    'docsdk.framework'
  );
  if (fs.existsSync(path.join(pluginSrc, 'docsdk'))) return pluginSrc;
  return null;
}


function syncDir(src, dest) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  const r = spawnSync(
    'rsync',
    ['-a', '--delete', `${src}${path.sep}`, `${dest}${path.sep}`],
    { stdio: 'inherit' }
  );
  if (r.status !== 0) {
    // Fallback when rsync is unavailable.
    fs.rmSync(dest, { recursive: true, force: true });
    fs.cpSync(src, dest, { recursive: true });
  }
}


/**
 * Always push DocumentReaderPlugin/.../docsdk.framework into:
 * - plugins/document-reader-cordova/... (so Cordova's next copy is fresh)
 * - platforms/ios/App/Plugins/... (what Xcode actually embeds)
 */
function syncDocsdkFramework(projectRoot) {
  const src = resolveDocsdkDropPath(projectRoot);
  if (!src) {
    console.warn(
      '[document-reader-cordova] missing docsdk.framework — place Drive unzip at DocumentReaderPlugin/src/ios/Frameworks/docsdk.framework'
    );
    return false;
  }


  const targets = [
    path.join(
      projectRoot,
      'plugins',
      PLUGIN_ID,
      'src',
      'ios',
      'Frameworks',
      'docsdk.framework'
    ),
    path.join(
      projectRoot,
      'platforms',
      'ios',
      'App',
      'Plugins',
      PLUGIN_ID,
      'docsdk.framework'
    ),
  ];


  let synced = 0;
  for (const dest of targets) {
    const parent = path.dirname(dest);
    if (!fs.existsSync(parent) && !dest.includes(`${path.sep}platforms${path.sep}`)) {
      fs.mkdirSync(parent, { recursive: true });
    }
    if (!fs.existsSync(parent)) continue;
    if (path.resolve(src) === path.resolve(dest)) continue;
    console.log(`[document-reader-cordova] syncing docsdk.framework → ${dest}`);
    syncDir(src, dest);
    synced += 1;
  }
  if (synced > 0) {
    console.log(
      `[document-reader-cordova] docsdk.framework synced from ${src} (${synced} target(s))`
    );
  }
  return synced > 0;
}


function writeExtras(projectRoot, teamId) {
  const cordovaDir = path.join(projectRoot, 'platforms', 'ios', 'cordova');
  if (!fs.existsSync(cordovaDir)) return;
  const lines = [
    '// Auto-generated by document-reader-cordova hooks/ios_prepare.js',
    `PRODUCT_BUNDLE_IDENTIFIER = ${IOS_BUNDLE_ID}`,
    'CODE_SIGN_STYLE = Automatic',
  ];
  if (teamId) lines.push(`DEVELOPMENT_TEAM = ${teamId}`);
  fs.writeFileSync(
    path.join(cordovaDir, 'build-extras.xcconfig'),
    lines.join('\n') + '\n'
  );


  // Also patch pbxproj so archive uses the licensed iOS bundle id
  // (widget id stays Android-compatible in config.xml).
  const pbx = path.join(
    projectRoot,
    'platforms',
    'ios',
    'App.xcodeproj',
    'project.pbxproj'
  );
  if (fs.existsSync(pbx)) {
    let text = fs.readFileSync(pbx, 'utf8');
    // Force licensed iOS bundle id (Cordova may reset from widget id without ios-CFBundleIdentifier).
    text = text.replace(
      /PRODUCT_BUNDLE_IDENTIFIER = "?[^";\n]+"?;/g,
      `PRODUCT_BUNDLE_IDENTIFIER = ${IOS_BUNDLE_ID};`
    );
    if (teamId) {
      if (/DEVELOPMENT_TEAM = /.test(text)) {
        text = text.replace(
          /DEVELOPMENT_TEAM = [^;]+;/g,
          `DEVELOPMENT_TEAM = ${teamId};`
        );
      } else if (/CODE_SIGN_STYLE = Automatic;/.test(text)) {
        text = text.replace(
          /CODE_SIGN_STYLE = Automatic;/g,
          `CODE_SIGN_STYLE = Automatic;\n\t\t\t\tDEVELOPMENT_TEAM = ${teamId};`
        );
      }
    }
    fs.writeFileSync(pbx, text);
  }
}


function writeSignScript(platformsIos) {
  const scriptsDir = path.join(platformsIos, 'scripts');
  fs.mkdirSync(scriptsDir, { recursive: true });
  const dest = path.join(scriptsDir, 'sign_nested_docsdk.sh');
  fs.writeFileSync(
    dest,
    `#!/bin/bash
set -euo pipefail
# Usage: sign_nested_docsdk.sh <path-to-docsdk.framework> [identity]
FW="\${1:?docsdk.framework path required}"
ID="\${2:-\${EXPANDED_CODE_SIGN_IDENTITY:-}}"
if [ -z "\$ID" ] || [ "\$ID" = "-" ]; then
  ID=\$(security find-identity -v -p codesigning 2>/dev/null | awk -F'"' '/Apple Development|iPhone Developer/{print \$2; exit}')
fi
if [ -z "\$ID" ]; then
  echo "error: no code signing identity" >&2
  exit 1
fi
sign_one() {
  local path="\$1"
  [ -d "\$path" ] || return 0
  if [ -d "\$path/Frameworks" ]; then
    for nested in "\$path/Frameworks"/*.framework; do
      [ -d "\$nested" ] || continue
      sign_one "\$nested"
    done
  fi
  echo "Signing \$(basename "\$path") with \$ID"
  /usr/bin/codesign --remove-signature "\$path" 2>/dev/null || true
  /usr/bin/codesign --force --sign "\$ID" --timestamp=none "\$path"
}
sign_one "\$FW"
`,
    { mode: 0o755 }
  );
  return dest;
}


function findApps(projectRoot) {
  const ios = path.join(projectRoot, 'platforms', 'ios');
  const hits = [];
  function walk(dir, depth) {
    if (depth > 6 || !fs.existsSync(dir)) return;
    for (const name of fs.readdirSync(dir)) {
      const full = path.join(dir, name);
      let st;
      try {
        st = fs.lstatSync(full);
      } catch {
        continue;
      }
      if (st.isSymbolicLink()) continue;
      if (name.endsWith('.app') && st.isDirectory()) hits.push(full);
      else if (st.isDirectory() && name !== 'node_modules') walk(full, depth + 1);
    }
  }
  walk(ios, 0);
  return hits;
}


function resignAppPreservingEntitlements(appPath) {
  const idOut = spawnSync(
    'security',
    ['find-identity', '-v', '-p', 'codesigning'],
    { encoding: 'utf8' }
  );
  const match = (idOut.stdout || '').match(
    /"(Apple Development[^"]+|iPhone Developer[^"]+)"/
  );
  const identity = match ? match[1] : null;
  if (!identity) return;
  const entFile = path.join(
    require('os').tmpdir(),
    `dr-cordova-entitlements-${process.pid}.plist`
  );
  spawnSync('codesign', ['-d', `--entitlements=:${entFile}`, appPath], {
    encoding: 'utf8',
  });
  const args = ['--force', '--sign', identity, '--timestamp=none'];
  if (fs.existsSync(entFile) && fs.statSync(entFile).size > 0) {
    args.push(`--entitlements=${entFile}`);
  } else {
    args.push('--preserve-metadata=identifier,entitlements,flags,runtime');
  }
  args.push(appPath);
  const r = spawnSync('codesign', args, { stdio: 'inherit' });
  try {
    fs.unlinkSync(entFile);
  } catch {
    // ignore
  }
  if (r.status !== 0) {
    console.warn(
      `[document-reader-cordova] warning: could not re-sign ${appPath} (status=${r.status})`
    );
  } else {
    console.log(`[document-reader-cordova] re-sealed ${path.basename(appPath)}`);
  }
}


function signBuiltApps(projectRoot) {
  const script = path.join(
    projectRoot,
    'platforms',
    'ios',
    'scripts',
    'sign_nested_docsdk.sh'
  );
  if (!fs.existsSync(script)) writeSignScript(path.join(projectRoot, 'platforms', 'ios'));
  const apps = findApps(projectRoot);
  let signed = 0;
  for (const app of apps) {
    const fw = path.join(app, 'Frameworks', 'docsdk.framework');
    if (!fs.existsSync(fw)) continue;
    console.log(`[document-reader-cordova] re-signing ${fw}`);
    const r = spawnSync('/bin/sh', [script, fw], { stdio: 'inherit' });
    if (r.status !== 0) process.exit(r.status == null ? 1 : r.status);
    resignAppPreservingEntitlements(app);
    signed += 1;
  }
  if (signed === 0) {
    console.log('[document-reader-cordova] note: no built docsdk.framework found to re-sign yet');
  }
}


function prepare(projectRoot) {
  // Refresh Drive runtime into platforms/plugins before Xcode embeds it.
  syncDocsdkFramework(projectRoot);
  const platformsIos = path.join(projectRoot, 'platforms', 'ios');
  if (!fs.existsSync(platformsIos)) return;
  const teamId = readTeamId(projectRoot);
  writeExtras(projectRoot, teamId);
  writeSignScript(platformsIos);
  console.log(
    `[document-reader-cordova] iOS extras: team=${teamId || '(none)'} bundle=${IOS_BUNDLE_ID}`
  );
}


module.exports = function (ctx) {
  const projectRoot =
    (ctx && ctx.opts && ctx.opts.projectRoot) ||
    process.argv[2] ||
    process.cwd();
  const hook = String(
    (ctx && (ctx.hook || ctx.type)) ||
      (ctx && ctx.opts && ctx.opts.hook) ||
      ''
  );
  prepare(projectRoot);
  // after_build: re-sign nested frameworks inside the produced .app
  if (hook.includes('after_build') || process.argv.includes('--sign')) {
    signBuiltApps(projectRoot);
  }
};


if (require.main === module) {
  const root = process.argv[2] || process.cwd();
  prepare(root);
  if (process.argv.includes('--sign')) signBuiltApps(root);
}
